cargo-features = ["trim-paths"]

[package]
name = "genvm-sdk-rust"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = "1.0.86"

[features]
default = []
std = []

[profile.release]
lto = "fat"
strip = "debuginfo"
incremental = false
codegen-units = 1
trim-paths = "all"
