name: Install rust
#
runs:
  using: composite
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: ""
        cache-workspaces: |
          genvm -> ../build/generated/rust-target
          runners/cpython-and-ext/extension -> ../../../build/generated/rust-target
          runners/softfloat/patch-floats -> ../../../build/generated/rust-target
