bind_address: 127.0.0.1:3032
webdriver_host: http://127.0.0.1:444

threads: 4
blocking_threads: 16

session_create_request: |
  "capabilities": {
    "alwaysMatch": {
      "browserName": "chrome",
      "goog:chromeOptions": {
        "args": ["--headless", "--disable-dev-shm-usage", "--no-zygote", "--no-sandbox"]
      }
    }
  }

extra_tld: []
always_allow_hosts:
  - genvm-test
