[package]
name = "genlayer_calldata"
version = "0.0.1"
edition = "2024"
repository = "https://github.com/genlayerlabs/genvm"
description = "Crate for handling GenLayer calldata encoding and decoding"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://genlayer.com"
keywords = ["genlayer", "blockchain", "smart-contracts", "wasm", "wasi"]
categories = ["api-bindings", "wasm"]
exclude = [
    "/tests/**",
]

[features]
default = []
arbitrary = ["dep:arbitrary"]

[dependencies]
hex = "0.4.3"
num-bigint = {version = "0.4.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
arbitrary = { version = "1.0", optional = true }
primitive-types = { version = "0.13", features = ["impl-serde"] }
bytes = {version = "1.11.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
