import typing
import os

if typing.TYPE_CHECKING or os.getenv('GENERATING_DOCS', 'false') == 'true':
	import collections.abc

	type _Fd = int
	type _FdErroring = int

	def rollback(s: str) -> typing.NoReturn: ...
	def contract_return(s: bytes) -> typing.NoReturn: ...

	def run_nondet(leader_data: bytes, validator_data: bytes) -> _Fd: ...

	def sandbox(data: bytes) -> _Fd: ...

	def call_contract(address: bytes, calldata: bytes, data: str) -> _Fd: ...
	def post_message(address: bytes, calldata: bytes, data: str) -> None: ...

	def deploy_contract(calldata: bytes, code: bytes, data: str) -> None: ...

	def eth_send(address: bytes, calldata: bytes, data: str) -> None: ...
	def eth_call(address: bytes, calldata: bytes) -> _Fd: ...

	def get_entrypoint() -> bytes: ...
	def get_message_data() -> str: ...

	def web_render(payload: str) -> _FdErroring: ...

	def exec_prompt(payload: str) -> _FdErroring: ...
	def exec_prompt_template(payload: str) -> _FdErroring: ...

	def storage_read(slot: bytes, off: int, len: int) -> bytes: ...
	def storage_write(slot: bytes, off: int, what: collections.abc.Buffer) -> bytes: ...

	def get_balance(address: bytes) -> int: ...

	def get_self_balance() -> int: ...
else:
	from _genlayer_wasi import *
