[env]
PYO3_USE_ABI3_FORWARD_COMPATIBILITY = "1"
PYO3_NO_PYTHON = "1"

[build]
rustflags =[
    # "-Clink-args=-export-all"
    # "-Ctarget-feature=-reference-types",
]

#[unstable]
#unstable-options = true
#build-std = ["core", "alloc", "std", "panic_abort"]
