name: GenVM get source
inputs:
  install_also:
    description: additional flags for install-deps.rb
    required: false
    default: ""
    type: string
runs:
  using: composite
  steps:
    - name: checkout submodules
      run: |
        cd "$GITHUB_WORKSPACE" && \
          (./build-scripts/install-deps.rb --os ${{ inputs.install_also }} || true) && \
          ./build-scripts/install-deps.rb --os ${{ inputs.install_also }} && \
          git config --global user.email "worker@ci.ci" && \
          git config --global user.name "CI worker" && \
          git submodule update --init --recursive && \
          source env.sh && \
          git third-party update --all
      shell: bash -ex {0}
