name: GenVM get source
description: ""
inputs:
  install_also:
    description: additional flags for install-deps.rb
    required: false
    default: ""
  load_submodules:
    description: if should update submodules
    required: false
    default: "true"
  third_party:
    description: third-party modules to install
    required: false
    default: --all
runs:
  using: composite
  steps:
    - name: checkout submodules
      run: |
        cd "$GITHUB_WORKSPACE"
        sudo apt-get update && sudo apt-get install -y ruby
        (./build-scripts/install/install-deps.rb --os || true)
        ./build-scripts/install/install-deps.rb --os ${{ inputs.install_also }}
        git config --global user.email "worker@ci.ci"
        git config --global user.name "CI worker"
        if [ "${{ inputs.load_submodules }}" == "true" ]
        then
          git submodule update --init --recursive --depth 1
          source env.sh
          git third-party update ${{ inputs.third_party }}
        fi
      shell: bash -ex {0}
