name: GenVM module tests
on:
  workflow_run:
    workflows: ["GenVM module tests"]
    types:
      - completed
defaults:
  run:
    shell: bash -x {0}

jobs:
  build-runners:
    runs-on: ubuntu-latest
    outputs:
      runners-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Get source
        uses: ./.github/actions/get-src
        with:
          install_also: --runners
      - name: Install rust
        uses: ./.github/actions/setup-rust
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: runners-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            runners-${{ runner.os }}-buildx-
      - name: Build
        run: |
          ./build-scripts/install-deps.rb --runners && \
          ya-build config && \
          ninja --verbose -C build tags/runner && \
          tree build/out && \
          pushd build/out && \
          zip -r -9 ../runners.zip * && \
          popd
      - name: Publish runners
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: runners
          path: ${{ github.workspace }}/build/runners.zip
