# This workflow is only triggered manually since the webdriver image has it's own (slow) lifecycle
name: Build and push webdriver image

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: new version to push

env:
  version: ${{ inputs.version }}

jobs:
  docker-image:
    name: Build and push webdriver image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yeagerai
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            yeagerai/genlayer-genvm-webdriver
          tags: |
            type=raw,value=${{ env.version }}
            type=raw,value=latest

      - name: Set up QEMU for docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: executor/modules/implementation/webdriver
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
