name: GenVM module tests
on:
  push:
    paths-ignore:
      - doc/**
defaults:
  run:
    shell: bash -x {0}
jobs:
  test-cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get source
        uses: ./.github/actions/get-src
      - name: Install rust
        uses: ./.github/actions/setup-rust
      - name: configure and run codegen
        run: |
          cd "$GITHUB_WORKSPACE" && ./tools/ya-build/ya-build config && \
          ninja -v -C build tags/codegen
      - name: check format
        run: |
          ./build-scripts/cargo-fmt.sh && \
          git diff -U1 --exit-code
      - name: cargo test
        run: |
          ./build-scripts/cargo-test.sh

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
      - name: Get source
        uses: ./.github/actions/get-src
      - name: install dependencies
        run: |
          python3.12 -m pip install poetry && \
            pushd runners/genlayer-std && \
            poetry install && \
            popd
      - name: pytest
        run: |
          pushd runners/genlayer-std && \
          poetry run pytest -n auto && \
          popd
