name: GenVM module tests
on:
  push:
    paths-ignore:
      - doc/**
defaults:
  run:
    shell: bash -x {0}
jobs:
  test-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: basic setup
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y --no-install-recommends ninja-build ruby curl git python3 zip wget tar tree && \
          git lfs install
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.80.0
          components: rustfmt
          target: wasm32-wasi
          rustflags: ""
          cache-workspaces: |
            genvm -> target
            sdk-python -> target
            tools/softfloat-lib/patch-floats -> target
      - name: checkout submodules
        run: |
          cd "$GITHUB_WORKSPACE" && \
            git config --global user.email "worker@ci.ci" && \
            git config --global user.name "CI worker" && \
            git submodule update --init --recursive && \
            ./tools/git-third-party/git-third-party update --all
      - name: configure and run codegen
        run: |
          cd "$GITHUB_WORKSPACE" && ./tools/ya-build/ya-build config && \
          ninja -v -C build tags/codegen
      - name: cargo test
        run: |
          ./build-scripts/cargo-test.sh

  test-python:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            sdk-python
            .genvm-monorepo-root
      - name: install dependencies
        run: |
          python3.12 -m pip install poetry && \
            pushd sdk-python && \
            poetry install && \
            popd
      - name: pytest
        run: |
          pushd sdk-python && \
          poetry run pytest -n auto && \
          popd
