name: GenVM pr
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
defaults:
  run:
    shell: bash -x {0}

jobs:
  initial:
    uses: ./.github/workflows/initial-template.yaml
    secrets: inherit

### MODULE TESTS

  module-test-cargo:
    needs: [initial]
    runs-on: ubuntu-latest
    if: needs.initial.outputs.rs-changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Get source
        uses: ./.github/actions/get-src
        with:
          install_also: --rust
      - name: configure and run codegen
        run: |
          cd "$GITHUB_WORKSPACE" && ./tools/ya-build/ya-build config && \
          ninja -v -C build tags/codegen
      - name: check format
        run: |
          ./build-scripts/cargo-fmt.sh && \
          git diff -U1 --exit-code
      - name: cargo test
        run: |
          ./build-scripts/cargo-test.sh
        env:
          OPENAIKEY: ${{ secrets.OPENAIKEY }}
          HEURISTKEY: ${{ secrets.HEURISTKEY }}
          ANTHROPICKEY: ${{ secrets.ANTHROPICKEY }}
          XAIKEY: ${{ secrets.XAIKEY }}
          GEMINIKEY: ${{ secrets.GEMINIKEY }}

  module-test-python:
    needs: [initial]
    runs-on: ubuntu-latest
    if: needs.initial.outputs.py-changed == 'true'
    permissions:
      pull-requests: write   # Needed for posting a comment
    steps:
      - run: sudo apt-get install -y python3-poetry
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: poetry
      - name: Get source
        uses: ./.github/actions/get-src
        with:
          load_submodules: "false"
      - name: install dependencies
        run: |
          python3.12 -m pip install poetry && \
            pushd runners/genlayer-py-std && \
            poetry install && \
            popd
      - name: pytest
        run: |
          pushd runners/genlayer-py-std && \
          echo "_(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_" > /tmp/py-cov.log && \
          echo '```' >> /tmp/py-cov.log && \
          poetry run pytest -n auto | tee -a /tmp/py-cov.log && \
          echo '```' >> /tmp/py-cov.log && \
          popd
      - name: report
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: /tmp/py-cov.log
          comment-tag: py-coverage

### END

  validate-end:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - initial
      - module-test-cargo
      - module-test-python
    steps:
      - run: |
          echo ${{ join(needs.*.result, ' ') }} | grep -vP 'failure|cancelled'
