name: Deploy Documentation to Pages

on:
  push:
    branches:
      - main
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DOCS_DOMAIN: 'sdk.genlayer.com'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: Gr1N/setup-poetry@v9

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: poetry

      - name: Get source
        uses: ./.github/actions/get-src
        with:
          load_submodules: "true"
          third_party: "none"

      - name: Install dependencies
        run: |
          python3.12 -m pip install poetry && \
            pushd build-scripts/doctypes/ && \
            poetry install && \
            popd

      - name: Configure and build documentation
        run: |
          ./tools/ya-build/ya-build config
          ninja -v -C build genvm/runners/docs genvm/runners/types

      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Prepare documentation
        run: |
          # Create combined docs directory
          mkdir -p _site

          # Copy HTML docs
          cp -r build/py-docs/docs/* _site/

          # Create py-types directory and copy py-types
          mkdir -p _site/py-types
          cp -r build/py-types/* _site/py-types/

          # Configure custom domain
          echo "${{ env.DOCS_DOMAIN }}" > _site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Purge Cloudflare cache
        if: success()
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
