name: Release GenVM

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  # workflow_dispatch:

defaults:
  run:
    shell: bash -x {0}

env:
  GCS_BUCKET: "gh-af"

jobs:
  build-runners:
    uses: ./.github/workflows/genvm-build-runners.yaml
    secrets: inherit

  release-build-genvm-release-ubuntu-latest:
    uses: ./.github/workflows/genvm-build-template.yaml
    secrets: inherit
    with:
      build_type: release
      runs_on: ubuntu-latest

  release-build-genvm-release-macos-latest:
    uses: ./.github/workflows/genvm-build-template.yaml
    secrets: inherit
    with:
      build_type: release
      runs_on: macos-latest

  release-publish:
    needs: [build-runners, release-build-genvm-release-ubuntu-latest, release-build-genvm-release-macos-latest]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - run: |
          wget -q ${{ needs.build-runners.outputs.artifact_url }} && \
          mv ${{ needs.build-runners.outputs.artifact_name }} genvm-runners.zip && \
          wget -q ${{ needs.release-build-genvm-release-ubuntu-latest.outputs.artifact_url }} && \
          mv ${{ needs.release-build-genvm-release-ubuntu-latest.outputs.artifact_name }} genvm-linux-amd64.zip && \
          wget -q ${{ needs.release-build-genvm-release-macos-latest.outputs.artifact_url }} && \
          mv ${{ needs.release-build-genvm-release-macos-latest.outputs.artifact_name }} genvm-macos-arm64.zip && \
          true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            genvm-runners.zip
            genvm-linux-amd64.zip
            genvm-macos-arm64.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
