name: GenVM release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  # workflow_dispatch:

defaults:
  run:
    shell: bash -x {0}

env:
  GCS_BUCKET: "gh-af"

jobs:
  build-runners:
    uses: ./.github/workflows/genvm-build-runners.yaml
    secrets: inherit

  release-build-genvm-release-ubuntu-latest:
    uses: ./.github/workflows/genvm-build-template.yaml
    secrets: inherit
    with:
      runs_on: ubuntu-latest
      preloads: --preload .ci/release-conf.rb
      install_also: ""

  release-build-genvm-release-ubuntu-latest-aarch64:
    uses: ./.github/workflows/genvm-build-template.yaml
    secrets: inherit
    with:
      runs_on: ubuntu-latest
      preloads: --preload .ci/release-conf.rb --preload .ci/executor-target-linux-aarch64.rb
      install_also: --cross-linux-aarch64

  release-build-genvm-release-macos-latest:
    uses: ./.github/workflows/genvm-build-template.yaml
    secrets: inherit
    with:
      runs_on: macos-latest
      preloads: --preload .ci/release-conf.rb
      install_also: ""

  release-data:
    uses: ./.github/workflows/genvm-build-data.yaml
    secrets: inherit

  release-publish:
    needs:
      - build-runners
      - release-build-genvm-release-ubuntu-latest
      - release-build-genvm-release-macos-latest
      - release-build-genvm-release-ubuntu-latest-aarch64
      - release-data
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - run: |
          curl -L --fail-with-body -H 'Accept: application/octet-stream' -o genvm-runners.zip ${{ needs.build-runners.outputs.artifact_url }} && \
          curl -L --fail-with-body -H 'Accept: application/octet-stream' -o genvm-linux-amd64.zip ${{ needs.release-build-genvm-release-ubuntu-latest.outputs.artifact_url }} && \
          curl -L --fail-with-body -H 'Accept: application/octet-stream' -o genvm-linux-arm64.zip ${{ needs.release-build-genvm-release-ubuntu-latest-aarch64.outputs.artifact_url }} && \
          curl -L --fail-with-body -H 'Accept: application/octet-stream' -o genvm-macos-arm64.zip ${{ needs.release-build-genvm-release-macos-latest.outputs.artifact_url }} && \
          curl -L --fail-with-body -H 'Accept: application/octet-stream' -o genvm-py-docs.zip  ${{ needs.release-data.outputs.docs_url }} && \
          curl -L --fail-with-body -H 'Accept: application/octet-stream' -o genvm-py-types.zip  ${{ needs.release-data.outputs.types_url }} && \
          true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            genvm-runners.zip
            genvm-linux-amd64.zip
            genvm-linux-arm64.zip
            genvm-macos-arm64.zip
            genvm-py-docs.zip
            genvm-py-types.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
