name: Semgrep OSS scan

on:
  push:
    branches:
      - main
      # - staging
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    # Skip any PR created by dependabot/renovatebot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    steps:
      - uses: actions/checkout@v4

      - id: semgrep_scan
        run: semgrep scan --config auto --text > semgrep.txt

      - name: DEBUG
        run: cat semgrep.txt

      - name: Install GitHub CLI
        run: sudo apt install -y gh

      - run: gh issue comment $ISSUE --body "Semgrep scan results:"
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

      # - name: Post SARIF Summary in the Pull Request
      #   run: |
      #     # Limit the length of the comment to avoid exceeding GitHub's max limit of 65536 characters
      #     SUMMARY=$(head -c 65000 semgrep.sarif)  # Trim SARIF content to 65,000 characters
      #     echo "$SUMMARY" > truncated_sarif.txt
      #     # Create a comment linking to the full SARIF file
      #     echo "Semgrep SARIF scan completed. [Download full SARIF report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts) for detailed results." > summary_comment.txt
      #     echo "" >> summary_comment.txt
      #     echo "Summary of SARIF file:" >> summary_comment.txt
      #     cat truncated_sarif.txt >> summary_comment.txt
      #     gh pr comment ${{ github.event.number }} --body "$(cat summary_comment.txt)"

      # - name: Post SARIF findings in the pull request
      #   if: github.event_name == 'pull_request'
      #   uses: sett-and-hive/sarif-to-comment-action@v2.0.1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: ${{ github.repository }}
      #     branch: ${{ github.head_ref }}
      #     pr-number: ${{ github.event.number }}
      #     sarif-file: semgrep.sarif
      #     title: Semgrep scan results
      #     dry-run: false
