name: Temp job
on:
  push:
    paths-ignore:
      - doc/**
defaults:
  run:
    shell: bash -x {0}

jobs:
  build-runners:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Get source
        uses: ./.github/actions/get-src
        with:
          install_also: --runners --rust
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          save-always: true
          path: /tmp/.buildx-cache
          key: runners-buildx-${{ github.sha }}
          restore-keys: |
            runners-buildx-
      - name: Configure
        run: |
          ./build-scripts/install-deps.rb --runners && \
          source env.sh && \
          ya-build config
      - name: Build extension
        run: |
          ninja --verbose -C build genvm/runners/cpython/extension && \
          git diff -U1 --exit-code
      - name: Build
        run: |
          ninja --verbose -C build tags/runner && \
          tree build/out && \
          pushd build/out && \
          zip -r -9 ../runners.zip * && \
          popd
      - name: Publish runners
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: runners
          path: ${{ github.workspace }}/build/runners.zip
